/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlbiblioteca;

/**
 *
 * @author willians
 */
public class Estudiantes extends javax.swing.JPanel {

    private String nombre;
    private String carne;
    private String carrera;
    private String fecha;
    /**
     * Creates new form Estudiantes
     */
    public Estudiantes() {
    }

    public Estudiantes(String nombre, String carne, String carrera, String fecha) {
        this.nombre = nombre;
        this.carne = carne;
        this.carrera = carrera;
        this.fecha = fecha;
    }

    public Estudiantes(String nombre, String carne, String carrera) {
        this.nombre = nombre;
        this.carne = carne;
        this.carrera = carrera;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
