/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlbiblioteca;
import java.awt.Container;
import java.awt.Graphics;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
/**
 *
 * @author bladimir
 */
public class Menu extends javax.swing.JFrame {
    public Image imagenFondo;
    public URL fondo;
    public Libros libro;
    public Estudiantes estudiante;
    public Prestamos1 prestamo;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        iniciarComponentes();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        estudiantesPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        botonBuscarE = new javax.swing.JButton();
        botonIngresarE = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        buscarEstudiante = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        buscarEText = new javax.swing.JTextField();
        tipoEBox = new javax.swing.JComboBox<>();
        botonBusquedaE = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ingresarEstudiante = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        librosPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        botonBuscarL = new javax.swing.JButton();
        botonIngresarL = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        buscarLibroPanel = new javax.swing.JPanel();
        libroL1 = new javax.swing.JLabel();
        libroL2 = new javax.swing.JLabel();
        tipoLBox = new javax.swing.JComboBox<>();
        buscarLText = new javax.swing.JTextField();
        buscarLBoton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        ingresarLibroPanel = new javax.swing.JPanel();
        libroL3 = new javax.swing.JLabel();
        libroL4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        libroTextTitulo = new javax.swing.JTextField();
        libroTextCodigo = new javax.swing.JTextField();
        libroTextAutor = new javax.swing.JTextField();
        libroTextEditorial = new javax.swing.JTextField();
        libroTextFecha = new javax.swing.JTextField();
        ingresarLBoton = new javax.swing.JButton();
        prestamosPanel = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        botonBuscarP = new javax.swing.JButton();
        botonNuevoP = new javax.swing.JButton();
        botonDevolverP = new javax.swing.JButton();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        buscarPrestamo = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        buscarPText = new javax.swing.JTextField();
        tipoPBox = new javax.swing.JComboBox<>();
        buscarPBoton = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        nuevoPrestamo = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        prestamoCodigoText = new javax.swing.JTextField();
        prestamoCarneText = new javax.swing.JTextField();
        prestamoFechaText = new javax.swing.JTextField();
        crearPrestamo = new javax.swing.JButton();
        devolverPrestamo = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        montoDinero = new javax.swing.JLabel();
        botonDevolucion = new javax.swing.JButton();
        buscarDevolucionText = new javax.swing.JTextField();
        tipoDevolucionPBox = new javax.swing.JComboBox<>();
        botonDevolver = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        archivosPanel = new javax.swing.JPanel();
        Aceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        reportesPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        generaReportesBox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(java.awt.Color.white);
        jTabbedPane1.setBorder(null);
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        estudiantesPanel.setBackground(new java.awt.Color(254, 254, 254));
        estudiantesPanel.setOpaque(false);

        jLabel4.setBackground(new java.awt.Color(254, 254, 254));
        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 22)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("¿Qué harás?");

        botonBuscarE.setText("Buscar");
        botonBuscarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarEActionPerformed(evt);
            }
        });
        jSplitPane1.setLeftComponent(botonBuscarE);

        botonIngresarE.setText("Ingresar");
        botonIngresarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarEActionPerformed(evt);
            }
        });
        jSplitPane1.setRightComponent(botonIngresarE);

        buscarEstudiante.setOpaque(false);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("¿Qué es lo que buscas?");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Busqueda por:");

        buscarEText.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        tipoEBox.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tipoEBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "Carné", "Carrera" }));

        botonBusquedaE.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        botonBusquedaE.setText("BUSCAR");
        botonBusquedaE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBusquedaEActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Carné", "Carrera", "Fecha de Nacimiento"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout buscarEstudianteLayout = new javax.swing.GroupLayout(buscarEstudiante);
        buscarEstudiante.setLayout(buscarEstudianteLayout);
        buscarEstudianteLayout.setHorizontalGroup(
            buscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarEstudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(buscarEstudianteLayout.createSequentialGroup()
                        .addGroup(buscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                            .addComponent(buscarEText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(buscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tipoEBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonBusquedaE)))
                .addContainerGap())
        );
        buscarEstudianteLayout.setVerticalGroup(
            buscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarEstudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarEText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoEBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBusquedaE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addContainerGap())
        );

        ingresarEstudiante.setOpaque(false);

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 22)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Datos");

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel9.setText("Nombre:");

        jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel10.setText("Carné:");

        jLabel11.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel11.setText("Fecha de nacimiento:");

        jLabel12.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel12.setText("Carrera:");

        jButton4.setText("INGRESAR");
        jButton4.setToolTipText("");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout ingresarEstudianteLayout = new javax.swing.GroupLayout(ingresarEstudiante);
        ingresarEstudiante.setLayout(ingresarEstudianteLayout);
        ingresarEstudianteLayout.setHorizontalGroup(
            ingresarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ingresarEstudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ingresarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ingresarEstudianteLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2))
                    .addGroup(ingresarEstudianteLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3))
                    .addGroup(ingresarEstudianteLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4))
                    .addGroup(ingresarEstudianteLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5)))
                .addContainerGap())
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ingresarEstudianteLayout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addGap(258, 258, 258))
        );
        ingresarEstudianteLayout.setVerticalGroup(
            ingresarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ingresarEstudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(30, 30, 30)
                .addGroup(ingresarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(ingresarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(ingresarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(ingresarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(buscarEstudiante, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(ingresarEstudiante, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(ingresarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(buscarEstudiante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ingresarEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(buscarEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout estudiantesPanelLayout = new javax.swing.GroupLayout(estudiantesPanel);
        estudiantesPanel.setLayout(estudiantesPanelLayout);
        estudiantesPanelLayout.setHorizontalGroup(
            estudiantesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(estudiantesPanelLayout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        estudiantesPanelLayout.setVerticalGroup(
            estudiantesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(estudiantesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1))
        );

        jTabbedPane1.addTab("Estudiantes", estudiantesPanel);

        librosPanel.setBackground(java.awt.Color.white);
        librosPanel.setBorder(null);
        librosPanel.setOpaque(false);

        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 22)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("¿Qué harás?");

        botonBuscarL.setText("Buscar");
        botonBuscarL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarLActionPerformed(evt);
            }
        });

        botonIngresarL.setText("Ingresar");
        botonIngresarL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarLActionPerformed(evt);
            }
        });

        buscarLibroPanel.setOpaque(false);

        libroL1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        libroL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        libroL1.setText("Ingresa lo que desees buscar:");

        libroL2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        libroL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        libroL2.setText("Busqueda por:");

        tipoLBox.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tipoLBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Titulo", "Autor", "Codigo", "Editorial" }));

        buscarLText.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        buscarLBoton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        buscarLBoton.setText("BUSCAR");
        buscarLBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarLBotonActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Titulo", "Autor", "Codigo del Libro", "Copias", "Fecha Publicacion", "Editorial"
            }
        ));
        jScrollPane5.setViewportView(jTable2);

        javax.swing.GroupLayout buscarLibroPanelLayout = new javax.swing.GroupLayout(buscarLibroPanel);
        buscarLibroPanel.setLayout(buscarLibroPanelLayout);
        buscarLibroPanelLayout.setHorizontalGroup(
            buscarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarLibroPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buscarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(buscarLibroPanelLayout.createSequentialGroup()
                        .addGroup(buscarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buscarLText)
                            .addComponent(libroL1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(buscarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tipoLBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(libroL2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buscarLBoton)))
                .addContainerGap())
        );
        buscarLibroPanelLayout.setVerticalGroup(
            buscarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarLibroPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buscarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(libroL1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(libroL2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buscarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarLText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarLBoton)
                    .addComponent(tipoLBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ingresarLibroPanel.setOpaque(false);

        libroL3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        libroL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        libroL3.setText("Datos");

        libroL4.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        libroL4.setText("Titulo del libro:");

        jLabel18.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel18.setText("Codigo del libro:");

        jLabel19.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel19.setText("Autor del libro:");

        jLabel20.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel20.setText("Editorial:");

        jLabel21.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel21.setText("Fecha de publicación:");

        ingresarLBoton.setText("INGRESAR");

        javax.swing.GroupLayout ingresarLibroPanelLayout = new javax.swing.GroupLayout(ingresarLibroPanel);
        ingresarLibroPanel.setLayout(ingresarLibroPanelLayout);
        ingresarLibroPanelLayout.setHorizontalGroup(
            ingresarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(libroL3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ingresarLibroPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ingresarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ingresarLibroPanelLayout.createSequentialGroup()
                        .addComponent(libroL4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(libroTextTitulo))
                    .addGroup(ingresarLibroPanelLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(libroTextAutor))
                    .addGroup(ingresarLibroPanelLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(libroTextCodigo))
                    .addGroup(ingresarLibroPanelLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(libroTextEditorial))
                    .addGroup(ingresarLibroPanelLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(libroTextFecha)))
                .addContainerGap())
            .addGroup(ingresarLibroPanelLayout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(ingresarLBoton)
                .addContainerGap(288, Short.MAX_VALUE))
        );
        ingresarLibroPanelLayout.setVerticalGroup(
            ingresarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ingresarLibroPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(libroL3)
                .addGap(18, 18, 18)
                .addGroup(ingresarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(libroL4)
                    .addComponent(libroTextTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ingresarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(libroTextAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ingresarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(libroTextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ingresarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(libroTextEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ingresarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(libroTextFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ingresarLBoton)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jLayeredPane2.setLayer(buscarLibroPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(ingresarLibroPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscarLibroPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ingresarLibroPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscarLibroPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ingresarLibroPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout librosPanelLayout = new javax.swing.GroupLayout(librosPanel);
        librosPanel.setLayout(librosPanelLayout);
        librosPanelLayout.setHorizontalGroup(
            librosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(librosPanelLayout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(botonBuscarL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonIngresarL)
                .addGap(0, 277, Short.MAX_VALUE))
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLayeredPane2)
        );
        librosPanelLayout.setVerticalGroup(
            librosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(librosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(librosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBuscarL)
                    .addComponent(botonIngresarL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane2))
        );

        jTabbedPane1.addTab("Libros", librosPanel);

        prestamosPanel.setBackground(java.awt.Color.white);
        prestamosPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        prestamosPanel.setOpaque(false);

        jLabel22.setFont(new java.awt.Font("Ubuntu", 1, 22)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("¿Qué harás?");

        botonBuscarP.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        botonBuscarP.setText("Buscar");
        botonBuscarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarPActionPerformed(evt);
            }
        });

        botonNuevoP.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        botonNuevoP.setText("Nuevo");
        botonNuevoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoPActionPerformed(evt);
            }
        });

        botonDevolverP.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        botonDevolverP.setText("Devolución");
        botonDevolverP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDevolverPActionPerformed(evt);
            }
        });

        buscarPrestamo.setOpaque(false);

        jLabel23.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Ingresa lo que desees buscar:");

        jLabel24.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Busqueda por:");

        buscarPText.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        tipoPBox.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tipoPBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Codigo del libro", "Carne del estudiante", "Fecha" }));
        tipoPBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoPBoxActionPerformed(evt);
            }
        });

        buscarPBoton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        buscarPBoton.setText("BUSCAR");
        buscarPBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPBotonActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo Libro", "Carné Estudiante", "Fecha Prestamo", "Monto a Pagar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable3);

        javax.swing.GroupLayout buscarPrestamoLayout = new javax.swing.GroupLayout(buscarPrestamo);
        buscarPrestamo.setLayout(buscarPrestamoLayout);
        buscarPrestamoLayout.setHorizontalGroup(
            buscarPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarPrestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buscarPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addGroup(buscarPrestamoLayout.createSequentialGroup()
                        .addGroup(buscarPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buscarPText)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(buscarPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tipoPBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarPBoton)))
                .addContainerGap())
        );
        buscarPrestamoLayout.setVerticalGroup(
            buscarPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarPrestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buscarPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buscarPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarPText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoPBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarPBoton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addContainerGap())
        );

        nuevoPrestamo.setOpaque(false);

        jLabel25.setFont(new java.awt.Font("Ubuntu", 1, 22)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Datos");

        jLabel26.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel26.setText("Codigo del libro:");

        jLabel27.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel27.setText("Carné del estudiante:");

        jLabel28.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel28.setText("Fecha del prestamo:");

        prestamoCodigoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prestamoCodigoTextActionPerformed(evt);
            }
        });

        crearPrestamo.setText("CREAR");
        crearPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearPrestamoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nuevoPrestamoLayout = new javax.swing.GroupLayout(nuevoPrestamo);
        nuevoPrestamo.setLayout(nuevoPrestamoLayout);
        nuevoPrestamoLayout.setHorizontalGroup(
            nuevoPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevoPrestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nuevoPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(nuevoPrestamoLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prestamoCodigoText))
                    .addGroup(nuevoPrestamoLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prestamoFechaText))
                    .addGroup(nuevoPrestamoLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prestamoCarneText)))
                .addContainerGap())
            .addGroup(nuevoPrestamoLayout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(crearPrestamo)
                .addContainerGap(317, Short.MAX_VALUE))
        );
        nuevoPrestamoLayout.setVerticalGroup(
            nuevoPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevoPrestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addGap(42, 42, 42)
                .addGroup(nuevoPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(prestamoCodigoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(nuevoPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(prestamoCarneText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(nuevoPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(prestamoFechaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(crearPrestamo)
                .addContainerGap())
        );

        devolverPrestamo.setOpaque(false);

        jLabel29.setFont(new java.awt.Font("Ubuntu", 1, 22)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Devolución de un libro");

        jLabel30.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Buscar libro a devolver:");

        jLabel31.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Busqueda por:");

        jLabel32.setText("MONTO A PAGAR:");

        montoDinero.setText("dinero");

        botonDevolucion.setText("BUSCAR");
        botonDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDevolucionActionPerformed(evt);
            }
        });

        buscarDevolucionText.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        tipoDevolucionPBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Codigo del libro", "Carne estudiante", "Fecha" }));

        botonDevolver.setText("DEVOLVER");

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane4.setViewportView(jTextArea3);

        javax.swing.GroupLayout devolverPrestamoLayout = new javax.swing.GroupLayout(devolverPrestamo);
        devolverPrestamo.setLayout(devolverPrestamoLayout);
        devolverPrestamoLayout.setHorizontalGroup(
            devolverPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, devolverPrestamoLayout.createSequentialGroup()
                .addGroup(devolverPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(devolverPrestamoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, devolverPrestamoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(devolverPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(devolverPrestamoLayout.createSequentialGroup()
                                .addGroup(devolverPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(buscarDevolucionText)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(devolverPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tipoDevolucionPBox, 0, 242, Short.MAX_VALUE)
                                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonDevolucion))
                            .addGroup(devolverPrestamoLayout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addGap(18, 18, 18)
                                .addComponent(montoDinero)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, devolverPrestamoLayout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(botonDevolver)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        devolverPrestamoLayout.setVerticalGroup(
            devolverPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(devolverPrestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addGap(26, 26, 26)
                .addGroup(devolverPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31))
                .addGap(18, 18, 18)
                .addGroup(devolverPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoDevolucionPBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarDevolucionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonDevolucion))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(devolverPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(montoDinero))
                .addGap(18, 18, 18)
                .addComponent(botonDevolver)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jLayeredPane3.setLayer(buscarPrestamo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(nuevoPrestamo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(devolverPrestamo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscarPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(nuevoPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(devolverPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscarPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(nuevoPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(devolverPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout prestamosPanelLayout = new javax.swing.GroupLayout(prestamosPanel);
        prestamosPanel.setLayout(prestamosPanelLayout);
        prestamosPanelLayout.setHorizontalGroup(
            prestamosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prestamosPanelLayout.createSequentialGroup()
                .addGroup(prestamosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(prestamosPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(prestamosPanelLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(botonBuscarP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonNuevoP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonDevolverP)
                        .addGap(0, 183, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jLayeredPane3)
        );
        prestamosPanelLayout.setVerticalGroup(
            prestamosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prestamosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(prestamosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBuscarP)
                    .addComponent(botonNuevoP)
                    .addComponent(botonDevolverP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane3))
        );

        jTabbedPane1.addTab("Prestamos", prestamosPanel);

        archivosPanel.setBackground(java.awt.Color.white);
        archivosPanel.setOpaque(false);

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        jLabel1.setText("Manejo de archivo");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel2.setText("archivos recividos");

        jLabel3.setText("archivos erroneos");

        javax.swing.GroupLayout archivosPanelLayout = new javax.swing.GroupLayout(archivosPanel);
        archivosPanel.setLayout(archivosPanelLayout);
        archivosPanelLayout.setHorizontalGroup(
            archivosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(archivosPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(archivosPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(archivosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(archivosPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Aceptar))
                    .addGroup(archivosPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(157, 157, 157)
                        .addGroup(archivosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        archivosPanelLayout.setVerticalGroup(
            archivosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(archivosPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(archivosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Aceptar)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addGroup(archivosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(archivosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cargar Archivo", archivosPanel);

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Generador de Reportes");

        generaReportesBox.setEditable(true);
        generaReportesBox.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        generaReportesBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Listado libros a devolver hoy", "Listado libros con mora", "Listado de libros prestados", "Monto recaudado por prestamos en un intervalo de tiempo", "Libros prestados por un estudiante", "Reporte libros prestados por carreras" }));

        jButton1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jButton1.setText("GENERAR");

        javax.swing.GroupLayout reportesPanelLayout = new javax.swing.GroupLayout(reportesPanel);
        reportesPanel.setLayout(reportesPanelLayout);
        reportesPanelLayout.setHorizontalGroup(
            reportesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reportesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reportesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                    .addGroup(reportesPanelLayout.createSequentialGroup()
                        .addComponent(generaReportesBox, 0, 1, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addGap(39, 39, 39))
        );
        reportesPanelLayout.setVerticalGroup(
            reportesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(reportesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generaReportesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(342, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Generar Reporte", reportesPanel);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 428));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controlbiblioteca/biblioteca3.jpg"))); // NOI18N
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        // busca el archivo
        CargarArchivo nuevo=new CargarArchivo();
        String a=nuevo.leerGrafico();
        String dato="LIBRO";
        int intIndex = dato.indexOf(a);
        if(intIndex == - 1){
            System.out.println("palabra encontrada");
            jTextArea1.append(a);
        }else{
            System.out.println("palabra no encontrada"
                + intIndex);
            jTextArea2.append(a);
        }
    }//GEN-LAST:event_AceptarActionPerformed

    private void crearPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearPrestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearPrestamoActionPerformed

    private void botonDevolverPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDevolverPActionPerformed
        botonBuscarP.setEnabled(true);
        botonNuevoP.setEnabled(true);
        botonDevolverP.setEnabled(false);
        buscarPrestamo.setVisible(false);
        devolverPrestamo.setVisible(true);
        nuevoPrestamo.setVisible(false);
    }//GEN-LAST:event_botonDevolverPActionPerformed

    private void botonNuevoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoPActionPerformed
        botonBuscarP.setEnabled(true);
        botonNuevoP.setEnabled(false);
        botonDevolverP.setEnabled(true);
        buscarPrestamo.setVisible(false);
        devolverPrestamo.setVisible(false);
        nuevoPrestamo.setVisible(true);
    }//GEN-LAST:event_botonNuevoPActionPerformed

    private void botonBuscarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarPActionPerformed
        botonBuscarP.setEnabled(false);
        botonNuevoP.setEnabled(true);
        botonDevolverP.setEnabled(true);
        buscarPrestamo.setVisible(true);
        devolverPrestamo.setVisible(false);
        nuevoPrestamo.setVisible(false);
    }//GEN-LAST:event_botonBuscarPActionPerformed

    private void botonIngresarLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarLActionPerformed
        botonBuscarL.setEnabled(true);
        botonIngresarL.setEnabled(false);
        buscarLibroPanel.setVisible(false);
        ingresarLibroPanel.setVisible(true);
    }//GEN-LAST:event_botonIngresarLActionPerformed

    private void botonBuscarLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarLActionPerformed
        botonBuscarL.setEnabled(false);
        botonIngresarL.setEnabled(true);
        buscarLibroPanel.setVisible(true);
        ingresarLibroPanel.setVisible(false);
    }//GEN-LAST:event_botonBuscarLActionPerformed

    private void botonIngresarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarEActionPerformed
        botonBuscarE.setEnabled(true);
        botonIngresarE.setEnabled(false);
        buscarEstudiante.setVisible(false);
        ingresarEstudiante.setVisible(true);
    }//GEN-LAST:event_botonIngresarEActionPerformed

    private void botonBuscarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarEActionPerformed
        botonBuscarE.setEnabled(false);
        botonIngresarE.setEnabled(true);
        buscarEstudiante.setVisible(true);
        ingresarEstudiante.setVisible(false);
    }//GEN-LAST:event_botonBuscarEActionPerformed

    private void tipoPBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoPBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoPBoxActionPerformed

    private void prestamoCodigoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prestamoCodigoTextActionPerformed
        
    }//GEN-LAST:event_prestamoCodigoTextActionPerformed

    private void botonBusquedaEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBusquedaEActionPerformed
        String estudianteVerifica = buscarEText.getText();
        String verificandoEstudiante1 = tipoEBox.getSelectedItem().toString();
        estudiante = new Estudiantes();
        estudiante.verificarEstudiante(verificandoEstudiante1, estudianteVerifica);
    }//GEN-LAST:event_botonBusquedaEActionPerformed

    private void buscarLBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarLBotonActionPerformed
        String libroVerifica = buscarLText.getText();
        String verificandoLibro = tipoLBox.getSelectedItem().toString();
        libro = new Libros();
        libro.verificarLibro1(verificandoLibro, libroVerifica);
    }//GEN-LAST:event_buscarLBotonActionPerformed

    private void buscarPBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPBotonActionPerformed
        String prestamoVerifica = buscarPText.getText();
        String verificandoPrestamo = tipoPBox.getSelectedItem().toString();
        prestamo = new Prestamos1();
        prestamo.verificarPrestamo1(verificandoPrestamo, prestamoVerifica);
    }//GEN-LAST:event_buscarPBotonActionPerformed

    private void botonDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDevolucionActionPerformed
        String devolverVerifica = buscarDevolucionText.getText();
        String verificandoDevolucion = tipoDevolucionPBox.getSelectedItem().toString();
        prestamo = new Prestamos1();
        prestamo.verificarPrestamo1(verificandoDevolucion, devolverVerifica);
    }//GEN-LAST:event_botonDevolucionActionPerformed

    private void iniciarComponentes(){
        ingresarLibroPanel.setVisible(false);
        buscarLibroPanel.setVisible(true);
        ingresarEstudiante.setVisible(false);
        buscarEstudiante.setVisible(true);
        botonBuscarE.setEnabled(false);
        botonIngresarE.setEnabled(true);
        nuevoPrestamo.setVisible(false);
        devolverPrestamo.setVisible(false);
        buscarPrestamo.setVisible(true);
        botonNuevoP.setEnabled(true);
        botonBuscarP.setEnabled(false);
        botonDevolverP.setEnabled(true);
        buscarLibroPanel.setOpaque(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JPanel archivosPanel;
    private javax.swing.JButton botonBuscarE;
    private javax.swing.JButton botonBuscarL;
    private javax.swing.JButton botonBuscarP;
    private javax.swing.JButton botonBusquedaE;
    private javax.swing.JButton botonDevolucion;
    private javax.swing.JButton botonDevolver;
    private javax.swing.JButton botonDevolverP;
    private javax.swing.JButton botonIngresarE;
    private javax.swing.JButton botonIngresarL;
    private javax.swing.JButton botonNuevoP;
    private javax.swing.JTextField buscarDevolucionText;
    private javax.swing.JTextField buscarEText;
    private javax.swing.JPanel buscarEstudiante;
    private javax.swing.JButton buscarLBoton;
    private javax.swing.JTextField buscarLText;
    private javax.swing.JPanel buscarLibroPanel;
    private javax.swing.JButton buscarPBoton;
    private javax.swing.JTextField buscarPText;
    private javax.swing.JPanel buscarPrestamo;
    private javax.swing.JButton crearPrestamo;
    private javax.swing.JPanel devolverPrestamo;
    private javax.swing.JPanel estudiantesPanel;
    private javax.swing.JComboBox<String> generaReportesBox;
    private javax.swing.JPanel ingresarEstudiante;
    private javax.swing.JButton ingresarLBoton;
    private javax.swing.JPanel ingresarLibroPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel libroL1;
    private javax.swing.JLabel libroL2;
    private javax.swing.JLabel libroL3;
    private javax.swing.JLabel libroL4;
    private javax.swing.JTextField libroTextAutor;
    private javax.swing.JTextField libroTextCodigo;
    private javax.swing.JTextField libroTextEditorial;
    private javax.swing.JTextField libroTextFecha;
    private javax.swing.JTextField libroTextTitulo;
    private javax.swing.JPanel librosPanel;
    private javax.swing.JLabel montoDinero;
    private javax.swing.JPanel nuevoPrestamo;
    private javax.swing.JTextField prestamoCarneText;
    private javax.swing.JTextField prestamoCodigoText;
    private javax.swing.JTextField prestamoFechaText;
    private javax.swing.JPanel prestamosPanel;
    private javax.swing.JPanel reportesPanel;
    private javax.swing.JComboBox<String> tipoDevolucionPBox;
    private javax.swing.JComboBox<String> tipoEBox;
    private javax.swing.JComboBox<String> tipoLBox;
    private javax.swing.JComboBox<String> tipoPBox;
    // End of variables declaration//GEN-END:variables
}
