/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlbiblioteca;
import java.awt.Container;
import java.awt.Graphics;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import FileManager.*;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
/**
 *
 * @author bladimir
 */
public class Menu extends javax.swing.JFrame {
    
    
    public Image imagenFondo;
    public URL fondo;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        
        txt_parametroL.setVisible(false);
        fondo = this.getClass().getResource("/controlbiblioteca/biblioteca3.png");
        imagenFondo = new ImageIcon(fondo).getImage();
        
        //add(panel5);
        iniciarComponentes();
    }
    public JPanel panel5 = new JPanel(){
    @Override
    public void paintComponent(Graphics g){
        g.drawImage(imagenFondo,getWidth(),getHeight(),this);
    }
    };
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        estudiantesPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        botonBuscarE = new javax.swing.JButton();
        botonIngresarE = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        buscarEstudiante = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        botonBusquedaE = new javax.swing.JButton();
        ingresarEstudiante = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        librosPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        botonBuscarL = new javax.swing.JButton();
        botonIngresarL = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        buscarLibroPanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        parametroL = new javax.swing.JFormattedTextField();
        txt_parametroL = new javax.swing.JTextField();
        ingresarLibroPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tituloLlibro = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        autorLibro = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        editorialLibro = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        fechaLibro = new javax.swing.JTextField();
        btn_IngresarLibro = new javax.swing.JButton();
        codigoLibro = new javax.swing.JFormattedTextField();
        jLabel35 = new javax.swing.JLabel();
        cantidadLibro = new javax.swing.JFormattedTextField();
        prestamosPanel = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        botonBuscarP = new javax.swing.JButton();
        botonNuevoP = new javax.swing.JButton();
        botonDevolverP = new javax.swing.JButton();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        buscarPrestamo = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton8 = new javax.swing.JButton();
        nuevoPrestamo = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        devolverPrestamo = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jTextField16 = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        archivosPanel = new javax.swing.JPanel();
        Aceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        estudiantesPanel.setBackground(new java.awt.Color(254, 254, 254));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 22)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("¿Qué harás?");

        botonBuscarE.setText("Buscar");
        botonBuscarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarEActionPerformed(evt);
            }
        });
        jSplitPane1.setLeftComponent(botonBuscarE);

        botonIngresarE.setText("Ingresar");
        botonIngresarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarEActionPerformed(evt);
            }
        });
        jSplitPane1.setRightComponent(botonIngresarE);

        buscarEstudiante.setOpaque(false);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("¿Qué es lo que buscas?");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Busqueda por:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "Carné", "Carrera" }));

        botonBusquedaE.setText("BUSCAR");

        javax.swing.GroupLayout buscarEstudianteLayout = new javax.swing.GroupLayout(buscarEstudiante);
        buscarEstudiante.setLayout(buscarEstudianteLayout);
        buscarEstudianteLayout.setHorizontalGroup(
            buscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarEstudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonBusquedaE)
                .addContainerGap())
        );
        buscarEstudianteLayout.setVerticalGroup(
            buscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarEstudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBusquedaE))
                .addContainerGap(267, Short.MAX_VALUE))
        );

        ingresarEstudiante.setOpaque(false);

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 22)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Datos");

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel9.setText("Nombre:");

        jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel10.setText("Carné:");

        jLabel11.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel11.setText("Fecha de nacimiento:");

        jLabel12.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel12.setText("Carrera:");

        jButton4.setText("INGRESAR");

        javax.swing.GroupLayout ingresarEstudianteLayout = new javax.swing.GroupLayout(ingresarEstudiante);
        ingresarEstudiante.setLayout(ingresarEstudianteLayout);
        ingresarEstudianteLayout.setHorizontalGroup(
            ingresarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ingresarEstudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ingresarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ingresarEstudianteLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2))
                    .addGroup(ingresarEstudianteLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3))
                    .addGroup(ingresarEstudianteLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4))
                    .addGroup(ingresarEstudianteLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5)))
                .addContainerGap())
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ingresarEstudianteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(221, 221, 221))
        );
        ingresarEstudianteLayout.setVerticalGroup(
            ingresarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ingresarEstudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(30, 30, 30)
                .addGroup(ingresarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(ingresarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(ingresarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(ingresarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(buscarEstudiante, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(ingresarEstudiante, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ingresarEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(buscarEstudiante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ingresarEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(buscarEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout estudiantesPanelLayout = new javax.swing.GroupLayout(estudiantesPanel);
        estudiantesPanel.setLayout(estudiantesPanelLayout);
        estudiantesPanelLayout.setHorizontalGroup(
            estudiantesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, estudiantesPanelLayout.createSequentialGroup()
                .addContainerGap(249, Short.MAX_VALUE)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(211, 211, 211))
        );
        estudiantesPanelLayout.setVerticalGroup(
            estudiantesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(estudiantesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1))
        );

        jTabbedPane1.addTab("Estudiantes", estudiantesPanel);

        librosPanel.setBackground(new java.awt.Color(254, 254, 254));

        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 22)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("¿Qué harás?");

        botonBuscarL.setText("Buscar");
        botonBuscarL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarLActionPerformed(evt);
            }
        });

        botonIngresarL.setText("Ingresar");
        botonIngresarL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarLActionPerformed(evt);
            }
        });

        buscarLibroPanel.setOpaque(false);

        jLabel14.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Ingresa lo que desees buscar:");

        jButton5.setText("BUSCAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Codigo", "Nombre", "Autor" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Busqueda por:");

        try {
            parametroL.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-UUU")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        parametroL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parametroLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buscarLibroPanelLayout = new javax.swing.GroupLayout(buscarLibroPanel);
        buscarLibroPanel.setLayout(buscarLibroPanelLayout);
        buscarLibroPanelLayout.setHorizontalGroup(
            buscarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarLibroPanelLayout.createSequentialGroup()
                .addGroup(buscarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buscarLibroPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buscarLibroPanelLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(buscarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_parametroL)
                            .addComponent(parametroL))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buscarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap())
        );
        buscarLibroPanelLayout.setVerticalGroup(
            buscarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarLibroPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buscarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buscarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parametroL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_parametroL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(284, Short.MAX_VALUE))
        );

        ingresarLibroPanel.setOpaque(false);

        jLabel16.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Datos");

        jLabel17.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel17.setText("Titulo del libro:");

        tituloLlibro.setText("jTextField7");

        jLabel18.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel18.setText("Codigo del libro:");

        jLabel19.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel19.setText("Autor del libro:");

        autorLibro.setText("jTextField9");

        jLabel20.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel20.setText("Editorial:");

        editorialLibro.setText("jTextField10");

        jLabel21.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel21.setText("Fecha de publicación:");

        fechaLibro.setText("jTextField11");

        btn_IngresarLibro.setText("INGRESAR");
        btn_IngresarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IngresarLibroActionPerformed(evt);
            }
        });

        try {
            codigoLibro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-UUU")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel35.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel35.setText("Cantidad:");

        cantidadLibro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        javax.swing.GroupLayout ingresarLibroPanelLayout = new javax.swing.GroupLayout(ingresarLibroPanel);
        ingresarLibroPanel.setLayout(ingresarLibroPanelLayout);
        ingresarLibroPanelLayout.setHorizontalGroup(
            ingresarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ingresarLibroPanelLayout.createSequentialGroup()
                .addGroup(ingresarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ingresarLibroPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ingresarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ingresarLibroPanelLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tituloLlibro))
                            .addGroup(ingresarLibroPanelLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(autorLibro))
                            .addGroup(ingresarLibroPanelLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(codigoLibro))
                            .addGroup(ingresarLibroPanelLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editorialLibro))
                            .addGroup(ingresarLibroPanelLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ingresarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cantidadLibro)
                                    .addComponent(fechaLibro, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)))))
                    .addGroup(ingresarLibroPanelLayout.createSequentialGroup()
                        .addGroup(ingresarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ingresarLibroPanelLayout.createSequentialGroup()
                                .addGap(230, 230, 230)
                                .addComponent(btn_IngresarLibro))
                            .addGroup(ingresarLibroPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel35)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ingresarLibroPanelLayout.setVerticalGroup(
            ingresarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ingresarLibroPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(ingresarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tituloLlibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ingresarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(autorLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ingresarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(codigoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ingresarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(editorialLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ingresarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(fechaLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ingresarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(cantidadLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(btn_IngresarLibro)
                .addContainerGap())
        );

        jLayeredPane2.setLayer(buscarLibroPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(ingresarLibroPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscarLibroPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ingresarLibroPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscarLibroPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ingresarLibroPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout librosPanelLayout = new javax.swing.GroupLayout(librosPanel);
        librosPanel.setLayout(librosPanelLayout);
        librosPanelLayout.setHorizontalGroup(
            librosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2)
            .addGroup(librosPanelLayout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(botonBuscarL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonIngresarL)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        librosPanelLayout.setVerticalGroup(
            librosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(librosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(librosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBuscarL)
                    .addComponent(botonIngresarL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane2))
        );

        jTabbedPane1.addTab("Libros", librosPanel);

        prestamosPanel.setOpaque(false);

        jLabel22.setFont(new java.awt.Font("Ubuntu", 1, 22)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("¿Qué harás?");

        botonBuscarP.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        botonBuscarP.setText("Buscar");
        botonBuscarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarPActionPerformed(evt);
            }
        });

        botonNuevoP.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        botonNuevoP.setText("Nuevo");
        botonNuevoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoPActionPerformed(evt);
            }
        });

        botonDevolverP.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        botonDevolverP.setText("Devolución");
        botonDevolverP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDevolverPActionPerformed(evt);
            }
        });

        buscarPrestamo.setOpaque(false);

        jLabel23.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Ingresa lo que desees buscar:");

        jTextField12.setText("jTextField12");

        jLabel24.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Busqueda por:");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton8.setText("BUSCAR");

        javax.swing.GroupLayout buscarPrestamoLayout = new javax.swing.GroupLayout(buscarPrestamo);
        buscarPrestamo.setLayout(buscarPrestamoLayout);
        buscarPrestamoLayout.setHorizontalGroup(
            buscarPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarPrestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buscarPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField12)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buscarPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addContainerGap())
        );
        buscarPrestamoLayout.setVerticalGroup(
            buscarPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarPrestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buscarPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buscarPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8))
                .addContainerGap(263, Short.MAX_VALUE))
        );

        nuevoPrestamo.setOpaque(false);

        jLabel25.setFont(new java.awt.Font("Ubuntu", 1, 22)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Datos");

        jLabel26.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel26.setText("Codigo del libro:");

        jLabel27.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel27.setText("Carné del estudiante:");

        jLabel28.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel28.setText("Fecha del prestamo:");

        jTextField13.setText("jTextField13");

        jTextField14.setText("jTextField14");

        jTextField15.setText("jTextField15");

        jButton9.setText("CREAR");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nuevoPrestamoLayout = new javax.swing.GroupLayout(nuevoPrestamo);
        nuevoPrestamo.setLayout(nuevoPrestamoLayout);
        nuevoPrestamoLayout.setHorizontalGroup(
            nuevoPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevoPrestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nuevoPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(nuevoPrestamoLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField13))
                    .addGroup(nuevoPrestamoLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField15))
                    .addGroup(nuevoPrestamoLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField14)))
                .addContainerGap())
            .addGroup(nuevoPrestamoLayout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jButton9)
                .addContainerGap(255, Short.MAX_VALUE))
        );
        nuevoPrestamoLayout.setVerticalGroup(
            nuevoPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevoPrestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addGap(42, 42, 42)
                .addGroup(nuevoPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(nuevoPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(nuevoPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addContainerGap())
        );

        devolverPrestamo.setOpaque(false);

        jLabel29.setFont(new java.awt.Font("Ubuntu", 1, 22)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Devolución de un libro");

        jLabel30.setText("Buscar libro a devolver:");

        jLabel31.setText("Busqueda por:");

        jButton10.setText("BUSCAR");

        jTextField16.setText("jTextField16");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel32.setText("MONTO A PAGAR:");

        jLabel33.setText("dinero");

        jButton11.setText("DEVOLVER");

        javax.swing.GroupLayout devolverPrestamoLayout = new javax.swing.GroupLayout(devolverPrestamo);
        devolverPrestamo.setLayout(devolverPrestamoLayout);
        devolverPrestamoLayout.setHorizontalGroup(
            devolverPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(devolverPrestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(devolverPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(devolverPrestamoLayout.createSequentialGroup()
                        .addGroup(devolverPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel32)
                            .addGroup(devolverPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField16)
                                .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(devolverPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(devolverPrestamoLayout.createSequentialGroup()
                                .addGroup(devolverPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton10))
                            .addGroup(devolverPrestamoLayout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(devolverPrestamoLayout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(jButton11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        devolverPrestamoLayout.setVerticalGroup(
            devolverPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(devolverPrestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addGap(77, 77, 77)
                .addGroup(devolverPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31))
                .addGap(18, 18, 18)
                .addGroup(devolverPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(devolverPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33))
                .addGap(18, 18, 18)
                .addComponent(jButton11)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jLayeredPane3.setLayer(buscarPrestamo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(nuevoPrestamo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(devolverPrestamo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscarPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(nuevoPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(devolverPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscarPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(nuevoPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(devolverPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout prestamosPanelLayout = new javax.swing.GroupLayout(prestamosPanel);
        prestamosPanel.setLayout(prestamosPanelLayout);
        prestamosPanelLayout.setHorizontalGroup(
            prestamosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prestamosPanelLayout.createSequentialGroup()
                .addGroup(prestamosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(prestamosPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(prestamosPanelLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(botonBuscarP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonNuevoP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonDevolverP)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(prestamosPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLayeredPane3)))
                .addContainerGap())
        );
        prestamosPanelLayout.setVerticalGroup(
            prestamosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prestamosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(prestamosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBuscarP)
                    .addComponent(botonNuevoP)
                    .addComponent(botonDevolverP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane3)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Prestamos", prestamosPanel);

        archivosPanel.setOpaque(false);

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        jLabel1.setText("Manejo de archivo");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel2.setText("archivos recividos");

        jLabel3.setText("archivos erroneos");

        javax.swing.GroupLayout archivosPanelLayout = new javax.swing.GroupLayout(archivosPanel);
        archivosPanel.setLayout(archivosPanelLayout);
        archivosPanelLayout.setHorizontalGroup(
            archivosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(archivosPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(archivosPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(archivosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(archivosPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Aceptar))
                    .addGroup(archivosPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(157, 157, 157)
                        .addGroup(archivosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        archivosPanelLayout.setVerticalGroup(
            archivosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(archivosPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(archivosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Aceptar)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addGroup(archivosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(archivosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cargar Archivo", archivosPanel);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 428));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controlbiblioteca/biblioteca3.jpg"))); // NOI18N
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        // busca el archivo
        CargarArchivo nuevo=new CargarArchivo();
        String a=nuevo.leerGrafico();
        String dato="LIBRO";
        int intIndex = dato.indexOf(a);
        if(intIndex == - 1){
            System.out.println("palabra encontrada");
            jTextArea1.append(a);
        }else{
            System.out.println("palabra no encontrada"
                + intIndex);
            jTextArea2.append(a);
        }
    }//GEN-LAST:event_AceptarActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void botonDevolverPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDevolverPActionPerformed
        botonBuscarP.setEnabled(true);
        botonNuevoP.setEnabled(true);
        botonDevolverP.setEnabled(false);
        buscarPrestamo.setVisible(false);
        devolverPrestamo.setVisible(true);
        nuevoPrestamo.setVisible(false);
    }//GEN-LAST:event_botonDevolverPActionPerformed

    private void botonNuevoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoPActionPerformed
        botonBuscarP.setEnabled(true);
        botonNuevoP.setEnabled(false);
        botonDevolverP.setEnabled(true);
        buscarPrestamo.setVisible(false);
        devolverPrestamo.setVisible(false);
        nuevoPrestamo.setVisible(true);
    }//GEN-LAST:event_botonNuevoPActionPerformed

    private void botonBuscarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarPActionPerformed
        botonBuscarP.setEnabled(false);
        botonNuevoP.setEnabled(true);
        botonDevolverP.setEnabled(true);
        buscarPrestamo.setVisible(true);
        devolverPrestamo.setVisible(false);
        nuevoPrestamo.setVisible(false);
    }//GEN-LAST:event_botonBuscarPActionPerformed

    private void botonIngresarLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarLActionPerformed
        botonBuscarL.setEnabled(true);
        botonIngresarL.setEnabled(false);
        buscarLibroPanel.setVisible(false);
        ingresarLibroPanel.setVisible(true);
    }//GEN-LAST:event_botonIngresarLActionPerformed

    private void botonBuscarLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarLActionPerformed
        botonBuscarL.setEnabled(false);
        botonIngresarL.setEnabled(true);
        buscarLibroPanel.setVisible(true);
        ingresarLibroPanel.setVisible(false);
        
       
    }//GEN-LAST:event_botonBuscarLActionPerformed

    private void botonIngresarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarEActionPerformed
        botonBuscarE.setEnabled(true);
        botonIngresarE.setEnabled(false);
        buscarEstudiante.setVisible(false);
        ingresarEstudiante.setVisible(true);
    }//GEN-LAST:event_botonIngresarEActionPerformed

    private void botonBuscarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarEActionPerformed
        botonBuscarE.setEnabled(false);
        botonIngresarE.setEnabled(true);
        buscarEstudiante.setVisible(true);
        ingresarEstudiante.setVisible(false);
    }//GEN-LAST:event_botonBuscarEActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Libros buscado = new Libros();
        ArrayList<Libros> libros = new ArrayList();
        
        String parametro =  parametroL.getText().trim();
        String codigo[];
        int tipo = jComboBox2.getSelectedIndex(); 
        if (!parametro.equals("")) {
            if (tipo == 0 && parametro.contains("-")) {
                codigo = parametro.trim().split("-");
                if (codigo.length == 2) {
                    if (!codigo[0].isEmpty() && !codigo[1].isEmpty()
                            && codigo[0].length()== 3 && codigo[1].length()==3
                        ) {
                        
                        libros = Buscador.buscarLibro(parametro, tipo, Libros.PATH);
                    } else {
                       JOptionPane.showMessageDialog(prestamosPanel, "Codigo invalido");
                    }
                } else {
                    JOptionPane.showMessageDialog(prestamosPanel, "Codigo invalido");
                }
            } else  {
                parametro = txt_parametroL.getText();
                libros = Buscador.buscarLibro(parametro, tipo, Libros.PATH);
            }
             if (libros.isEmpty()) {
                    JOptionPane.showMessageDialog(prestamosPanel, "Libro inexistente");
                } else {
                    for (Libros encontrado : libros) {
                        System.out.println(encontrado.toString());
                    }
                }
        } else {
            JOptionPane.showMessageDialog(prestamosPanel, "Parametro de busqueda invalido");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        
        
        parametroL.setText("");
        txt_parametroL.setText("");
        int tipo = jComboBox2.getSelectedIndex();
        
            switch (tipo) {
            case 0:
        
                parametroL.setVisible(true);
                txt_parametroL.setVisible(false);
                break;
            case 1:
                parametroL.setVisible(false);
                txt_parametroL.setVisible(true);
                break;
            case 2:
                parametroL.setVisible(false);               
                txt_parametroL.setVisible(true);
                break;
            }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void btn_IngresarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IngresarLibroActionPerformed
        String titulo;
        String autor;
        String editorial;
        String codigo;
        String fecha;
        int cantidad;
        
        titulo = tituloLlibro.getText();
        autor = autorLibro.getText();
        editorial = editorialLibro.getText();
        codigo = codigoLibro.getText();
        fecha = fechaLibro.getText();
        cantidad = Integer.valueOf(cantidadLibro.getText());
        Libros libro = new Libros(titulo, autor, codigo, cantidad, fecha, editorial);
        Controlador.guardar(libro,Libros.PATH + "/" + libro.getCodigo() +
                Controlador.EXT);
    }//GEN-LAST:event_btn_IngresarLibroActionPerformed

    private void parametroLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parametroLActionPerformed
//         try {
//            parametroL.commitEdit();
//        } catch (ParseException ex) {
//            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_parametroLActionPerformed

    private void iniciarComponentes(){
        ingresarLibroPanel.setVisible(false);
        buscarLibroPanel.setVisible(true);
        ingresarEstudiante.setVisible(false);
        buscarEstudiante.setVisible(true);
        botonBuscarE.setEnabled(false);
        botonIngresarE.setEnabled(true);
        nuevoPrestamo.setVisible(false);
        devolverPrestamo.setVisible(false);
        buscarPrestamo.setVisible(true);
        botonNuevoP.setEnabled(true);
        botonBuscarP.setEnabled(false);
        botonDevolverP.setEnabled(true);
        buscarLibroPanel.setOpaque(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JPanel archivosPanel;
    private javax.swing.JTextField autorLibro;
    private javax.swing.JButton botonBuscarE;
    private javax.swing.JButton botonBuscarL;
    private javax.swing.JButton botonBuscarP;
    private javax.swing.JButton botonBusquedaE;
    private javax.swing.JButton botonDevolverP;
    private javax.swing.JButton botonIngresarE;
    private javax.swing.JButton botonIngresarL;
    private javax.swing.JButton botonNuevoP;
    private javax.swing.JButton btn_IngresarLibro;
    private javax.swing.JPanel buscarEstudiante;
    private javax.swing.JPanel buscarLibroPanel;
    private javax.swing.JPanel buscarPrestamo;
    private javax.swing.JFormattedTextField cantidadLibro;
    private javax.swing.JFormattedTextField codigoLibro;
    private javax.swing.JPanel devolverPrestamo;
    private javax.swing.JTextField editorialLibro;
    private javax.swing.JPanel estudiantesPanel;
    private javax.swing.JTextField fechaLibro;
    private javax.swing.JPanel ingresarEstudiante;
    private javax.swing.JPanel ingresarLibroPanel;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JPanel librosPanel;
    private javax.swing.JPanel nuevoPrestamo;
    private javax.swing.JFormattedTextField parametroL;
    private javax.swing.JPanel prestamosPanel;
    private javax.swing.JTextField tituloLlibro;
    private javax.swing.JTextField txt_parametroL;
    // End of variables declaration//GEN-END:variables
}
